[features]
seeds = false
skip-lint = false
[programs.devnet]
news = "9KArRP6rGRxTwzaHTDQ5FRgWBYGQcHEJPseSHk8v48dk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
